var express = require('express');
var path = require('path');
var AV = require('leanengine');
require('./cloud');
var app = express();
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(express.static(path.join(__dirname, 'public')));
app.use(AV.express());
app.enable('trust proxy');
app.use(AV.Cloud.HttpsRedirect());
app.use('/', require('./routes/index'));
app.use('/auth', require('./routes/auth'));
app.use('/verify', require('./routes/verify'));
app.use('/reset', require('./routes/reset'));
app.use('/*', require('./routes/main'));
module.exports = app;